inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
