(require 'package)
(package-initialize)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))

(defun fetch-and-load-theme (theme-name)
  (package-refresh-contents)
  (setq pkg (make-symbol (concat theme-name "-theme")))
  (unless (package-installed-p pkg) (package-install pkg))

  (message "about to load theme")
  (load-theme (intern theme-name) t)
  (find-file (concat default-directory "lib/sample.js"))
  (redisplay t)
  (sleep-for 1)
  (async-shell-command (concat "screencapture -x " default-directory "../app/assets/images/" theme-name ".jpg"))
  (disable-theme theme-name)
  (switch-to-buffer "take-screenshot.el")
  )
